version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: foodorder_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - foodorder_app_data:/var/lib/postgresql/data

  smtp4dev:
    image: rnwood/smtp4dev:latest
    ports:
      - "3113:80"
      - "2525:25"

volumes:
  foodorder_app_data:
